// Program error codes and reasons, synchronized with the generated IDL.
export const VetoErrorCode = {
  "CapMustBePositive": 6000,
  "PerTxMaxMustBePositive": 6001,
  "PerTxMaxAboveCap": 6002,
  "ExpiryInThePast": 6003,
  "PurposeTooLong": 6004,
  "MerchantRequired": 6005,
  "AgentMustNotBeOwner": 6006,
  "SourceNotOwnedByOwner": 6007,
  "MintMismatch": 6008,
  "SourceMismatch": 6009,
  "LedgerMismatch": 6010,
  "NotTheAgent": 6011,
  "NotTheOwner": 6012,
  "InvalidMandatePda": 6013,
  "MandateNotActive": 6014,
  "MandateStillActive": 6015,
  "NonceRequired": 6016,
  "AmountMustBePositive": 6017,
  "OverrideAboveCap": 6018,
  "MathOverflow": 6019,
  "NonceAlreadySettled": 6020,
  "DelayNotAllowed": 6021,
  "ShareOutOfRange": 6022,
  "SafeAddressRequired": 6023,
  "GuardianIsOwner": 6024,
  "PositiveAmountRequired": 6025,
  "HoldMathOverflow": 6026,
  "NotTheVaultOwner": 6027,
  "NotOwnerOrGuardian": 6028,
  "NotTheGuardian": 6029,
  "BothKeysRequired": 6030,
  "InvalidVaultPda": 6031,
  "VaultTokenMismatch": 6032,
  "HoldMintMismatch": 6033,
  "HoldSourceNotOwned": 6034,
  "DestinationIsVault": 6035,
  "DestinationMismatch": 6036,
  "NotTheSafeAddress": 6037,
  "WithdrawalNotPending": 6038,
  "TooEarly": 6039,
  "VaultFrozen": 6040,
  "NotFrozen": 6041,
  "UnfreezeNotReady": 6042,
  "ChangeAlreadyPending": 6043,
  "NoPendingChange": 6044,
  "ChangeNotReady": 6045,
  "ChangeUnchanged": 6046,
  "NothingToRecover": 6047,
  "HoldInsufficientFunds": 6048,
  "BadVaultAuthority": 6049,
  "InvalidTradeRulePda": 6050,
  "TradeDeltaMismatch": 6051,
  "PoolAccountMismatch": 6052,
  "TradeLimitsOutOfOrder": 6053,
  "FloorDenominatorRequired": 6054,
  "ExchangeNotSupported": 6055,
  "DestinationNotOwnedByOwner": 6056,
  "UnexpectedTradeAccount": 6057,
  "TradeRuleNotActive": 6058,
  "TradeRuleStillActive": 6059,
  "FloorRequired": 6060,
  "DailyLimitRequired": 6061,
  "SourceAlreadyDelegated": 6062,
  "NotATokenAccount": 6063,
  "InvalidLegacyHoldLayout": 6064,
  "HoldWithdrawalPending": 6065,
  "SafeAddressIsGuardian": 6066,
  "SafeAddressIsOwner": 6067
} as const;

export const VetoErrorMessage = {
  "CapMustBePositive": "cap must be greater than zero",
  "PerTxMaxMustBePositive": "per-payment maximum must be greater than zero",
  "PerTxMaxAboveCap": "per-payment maximum cannot exceed the cap",
  "ExpiryInThePast": "expiry must be in the future",
  "PurposeTooLong": "purpose is longer than the on-chain limit",
  "MerchantRequired": "a mandate must name the merchant it may pay",
  "AgentMustNotBeOwner": "the agent key must not be the owner key",
  "SourceNotOwnedByOwner": "source token account is not owned by the mandate owner",
  "MintMismatch": "token mint does not match the mandate",
  "SourceMismatch": "source token account does not match the mandate",
  "LedgerMismatch": "ledger does not belong to this mandate",
  "NotTheAgent": "signer is not the agent named in the mandate",
  "NotTheOwner": "signer is not the owner of this mandate",
  "InvalidMandatePda": "mandate address does not match its stored fields",
  "MandateNotActive": "mandate is not active",
  "MandateStillActive": "mandate is still active",
  "NonceRequired": "an override needs a non-zero nonce",
  "AmountMustBePositive": "amount must be greater than zero",
  "OverrideAboveCap": "an override cannot raise the total cap",
  "MathOverflow": "arithmetic overflow",
  "NonceAlreadySettled": "override nonce is at or below the last paid nonce",
  "DelayNotAllowed": "delay must be 1, 2, or 3 days",
  "ShareOutOfRange": "share must be between 0 and 10000 basis points",
  "SafeAddressRequired": "safe address is required",
  "GuardianIsOwner": "the guardian must be a different key from the owner",
  "PositiveAmountRequired": "amount must be greater than zero",
  "HoldMathOverflow": "arithmetic overflow",
  "NotTheVaultOwner": "signer is not the owner of this vault",
  "NotOwnerOrGuardian": "signer is not the owner or the guardian",
  "NotTheGuardian": "signer is not the guardian",
  "BothKeysRequired": "both the owner and the guardian must sign",
  "InvalidVaultPda": "vault address does not match its stored fields",
  "VaultTokenMismatch": "vault token account does not match the vault",
  "HoldMintMismatch": "token mint does not match the vault",
  "HoldSourceNotOwned": "source token account is not owned by the vault owner",
  "DestinationIsVault": "destination is the vault token account",
  "DestinationMismatch": "destination does not match the pending withdrawal",
  "NotTheSafeAddress": "destination is not the safe address",
  "WithdrawalNotPending": "withdrawal is not pending",
  "TooEarly": "the chain clock has not reached the unlock time",
  "VaultFrozen": "the vault is frozen",
  "NotFrozen": "the vault is not frozen",
  "UnfreezeNotReady": "unfreeze is still waiting on the chain clock",
  "ChangeAlreadyPending": "a loosening change is already pending",
  "NoPendingChange": "there is no pending change",
  "ChangeNotReady": "the chain clock has not reached the change",
  "ChangeUnchanged": "the proposed values match the current rules",
  "NothingToRecover": "the vault token account is empty",
  "HoldInsufficientFunds": "the vault cannot cover this withdrawal",
  "BadVaultAuthority": "token account authority is not the vault",
  "InvalidTradeRulePda": "trade rule address does not match its stored fields",
  "TradeDeltaMismatch": "the swap moved a different amount than the rule allowed",
  "PoolAccountMismatch": "pool accounts do not match the trade rule",
  "TradeLimitsOutOfOrder": "per-trade maximum, daily limit, and cap are out of order",
  "FloorDenominatorRequired": "floor denominator must be greater than zero",
  "ExchangeNotSupported": "this exchange is not supported",
  "DestinationNotOwnedByOwner": "destination token account is not owned by the rule owner",
  "UnexpectedTradeAccount": "an extra account was passed to trade",
  "TradeRuleNotActive": "trade rule is not active",
  "TradeRuleStillActive": "trade rule is still active",
  "FloorRequired": "floor numerator must be greater than zero",
  "DailyLimitRequired": "daily limit must be greater than zero",
  "SourceAlreadyDelegated": "source token account is already delegated to another account",
  "NotATokenAccount": "account is not an initialized SPL token account",
  "InvalidLegacyHoldLayout": "vault is not the supported legacy Hold layout",
  "HoldWithdrawalPending": "a held withdrawal must be resolved before closing",
  "SafeAddressIsGuardian": "safe address must differ from the guardian",
  "SafeAddressIsOwner": "safe address must differ from the owner"
} as const;

export type VetoErrorName = keyof typeof VetoErrorCode;
